[tools]
bat = "latest"
fd = "latest"
go = "latest"
java = "latest"
node = "latest"
rust = "latest"
starship = "latest"
ghq = "latest"
stylua = "latest"
ruff = "latest"
golangci-lint = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:eslint_d" = "latest"
