[tools]
go = "latest"
node = "latest"
rust = "latest"
starship = "latest"
ghq = "latest"
stylua = "latest"
ruff = "latest"
golangci-lint = "latest"
"npm:prettierd" = "latest"
"npm:eslint_d" = "latest"
